# Generated by Django 5.2.12 on 2026-03-31 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_learning_outcome_lesson_standard_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='accuracy_score',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='dimensioning_score',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='line_weight_score',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='neatness_score',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='angle_precision_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='elliptical_accuracy_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='line_technique_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='scale_accuracy_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='standard_ref',
            field=models.CharField(default='ISO 5456 / ISO 128', max_length=100),
        ),
    ]
