# Generated by Django 5.2.12 on 2026-04-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_assignmentsubmission_accuracy_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='model_file',
            field=models.FileField(blank=True, help_text='Upload .glb, .gltf, or .stl files', null=True, upload_to='lesson_models/'),
        ),
    ]
